spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  output:
    ansi:
      enabled: Always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  servlet:
    context-path: /blood-bank
