spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  output:
    ansi:
      enabled: Always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml